### ISSUE TITLE
Downgrade Node version to have more compatibility

### ISSUE THREAD

**Issue by gijsroge** [Intracto/lint-config-intracto#3]
When i try to implement this in current projects that uses Node 10.x I get errors requiring Node >12. Is this necessary? Maybe we should allow node >8?

This applies to both https://github.com/Intracto/eslint-config-intracto and https://github.com/Intracto/stylelint-config-intracto

Thoughts?

**Comment by ioulian** [comment]
The latest eslint requires Node [v 10 or 12+](https://github.com/eslint/eslint/blob/master/package.json#L143)

The latest prettier requires Node [v8+](https://github.com/prettier/prettier/blob/master/package.json#L12)

v10 is the lowest we can support

**Comment by ioulian** [comment]
Lowered node requirements to Node v^10.12: 7ac5be9992697a864b2d5ac9b9f870e12fb2704d
